How do you perform pattern matching in Python? Explain

Import the regex module with import re.
Create a Regex object with the re. compile() function. ...
Pass the string you want to search into the Regex object's search() method. ...
Call the Match object's group() method to return a string of the actual matched text.